### ISSUE TITLE
how to create custom walpapers

### ISSUE THREAD

**Issue by Dazigion** [lucasax/Zero#9]
step by step please  
presuming that i have the png ready

**Comment by salman-apk** [comment]
If you have _Photoshop_ installed on your computer just place that `.png` file in a new file canvas with the size of `2000x2000` and adjust the image to fit. Now basically u need to make layers like these I made:

![image](https://user-images.githubusercontent.com/56877461/181630701-6f6e0624-f8a4-4a1d-a95b-d5b7ecafa23f.png)

- After you make them just export them separately:

![image](https://user-images.githubusercontent.com/56877461/181630950-742f724b-7424-4448-a78d-275661fb4128.png)

You also have to make a _thumbnail image_ of `5000x5000` although you can use a lower size it should be of the same values as `500x500` or `200x200`. A video with the file extension of `.mp4` is required for the preview of the wallpaper but that's optional and up to you. 

- The next step is to compress both images which you earlier exported into a single `.zip` file.

![image](https://user-images.githubusercontent.com/56877461/181632771-e83a43d0-32d8-4f76-847d-a795cfadcdc6.png)


- After that, you have completed all the above instructions mentioned you now have to add values into the `catalog.json` file:

![image](https://user-images.githubusercontent.com/56877461/181633583-b5eced3f-a743-4f48-b36d-c35028357e62.png)

- The `id` here refers to the `.zip` file name and both values should be the same.
- You can edit the `title,` `author,` and `site link of the author` (If you don't want to add the author's website just leave it blank).
- The wallpapers are currently hosted on **GitHub** but you can host them on any server.

### Greetings :)

**Comment by Dazigion** [comment]
thanks, set up everything to a fork
how to change on where the wallpapers hosted?
i have no clue on how this works

**Comment by salman-apk** [comment]
You just need this folder in case you have decided to host wallpapers on **Github**:
![image](https://user-images.githubusercontent.com/56877461/182608607-9d7bd0c3-02cc-48a9-8635-8a1445d97196.png)

The next thing you have to do is load the project in your `Android Studio` or any other `IDE` 
Then look for the `Constants.java` file inside your **app module** just change the `String URL_API` value link to the link where you have hosted, in your case it would be `https://github.com/Dazigion/zero/blob/master/wallpapers/`

![image](https://user-images.githubusercontent.com/56877461/182609386-a67d0c59-835d-4ae3-aac5-4f31277acdf1.png)

Don't edit anything else just make  sure that your repository is **public**, you haven't made it public yet just do to your repository and look for **settings** and then scroll down and you will find something like this: 

![image](https://user-images.githubusercontent.com/56877461/182610219-1e4d194f-3e9b-4ea8-b7e5-3d29f9a53432.png)

Change the **visibility** and you are good to go :)

**Comment by Dazigion** [comment]
thanks!
